### ISSUE TITLE
Add option to have pre and post minutes for recording

### ISSUE THREAD

**Issue by markwilkie** [markwilkie/StreamCapture#2]
When recording with keywords, there's not mechanism to adjust the recording time to account for things like over time etc.  The current idea is to optionally allow a pre and post minute directive with the keyword itself.  For example, Chelsea|5|30 would start recording 5 minutes early and end 1/2 hour late.

**Comment by markwilkie** [comment]
Done.  Added options to each keyword entry

**Comment by tomxslo** [comment]
$ ./StreamCapture.exe --keywords "Patrick" |5|30
bash: 5: command not found
bash: 30: command not found

`MainAsync =====================
Show: The Dan Patrick Show StartDT: 30.1.2017 15:00:00  Duration: 210
File: TheDanPatrickShow169256
Channels: 11 (hqlq) 
30.1.2017 14:24:12: Starting recording at 30.1.2017 15:00:00 - Waiting for 0 Days, 0 Hours, and 35 minutes.
`

**Comment by markwilkie** [comment]
Adding double quotes around the entire entry makes it work.
