### ISSUE TITLE
retentionDays only delete files in log directory

### ISSUE THREAD

**Issue by tomxslo** [markwilkie/StreamCapture#26]
I set  "retentionDays": 1 and program only delete old logs - old videos are still in video folder - mabye because of error i got? #23

**Comment by markwilkie** [comment]
The retention stuff is only executed in mode2 every time the program "wakes up" to check the schedule.  Please reopen if this does not explain it as it seems to work for me.

**Comment by tomxslo** [comment]
Smt don't work on my side with this cleaning:
"outputPath":"D:\\Database\\Recording",

My output folder:
![image](https://cloud.githubusercontent.com/assets/25433215/22851795/330f35b4-f02d-11e6-8fb2-31f51db6b9ce.png)

StreamCapture output:
`11.2.2017 7:38:28: StreamCapture Version 0.9  2/9/2017
11.2.2017 7:38:28: Verifying appsettings....
11.2.2017 7:38:28: Using keywords.json to search schedule. (Please run with --help if you're
=======================
11.2.2017 7:38:30: Queuing show: EFL: Wolverhampton Wanderers v Newcastle United
                      Starting on 11.2.2017 18:25:00 for 140 minutes (2hrs ish)
                      Channel list is: 113 (720p/uk)  38 (720p/us)  46 (hqlq/us)
11.2.2017 7:38:30: Queuing show: EFL: Leeds United v Cardiff City
                      Starting on 11.2.2017 15:55:00 for 140 minutes (2hrs ish)
                      Channel list is: 62 (/us)
11.2.2017 7:38:32: Checking for files older than 4.2.2017 7:38:32
11.2.2017 7:38:32: Now sleeping for 6 hours before checking again at 11.2.2017 13:00:00
`

**Comment by markwilkie** [comment]
done
