### ISSUE TITLE
adding channelPref in keywords.json

### ISSUE THREAD

**Issue by tomxslo** [markwilkie/StreamCapture#33]
It would be really great if you can add channelPref in keyword.json. 
I have trouble today, cause i would like to record 113 channel from 20:00 till 00:00 (mnf show)
I set 
```
{
  "MNF": {
    "keywords": "EPL",
    "exclude": "",
    "preMinutes": 10,
    "postMinutes": 120,
    "langPref": "UK",
    "qualityPref": "720P"
  },
```
(don't know why 01 channel is set like uk language - schedule on ss say:
```
13th 21:00-23:00 | #01 | EPL: Bournemouth v Manchester City (01 (720P / US) ; 11 (HQLQ / US) ; 21 (HQLQ / CA) ; 78 (720P / CA) ; 113 (720P / UK)))```
```

Program logs - it will record 01 channel for sure.
```
13.2.2017 13:30:50: Queuing show: EPL: Bournemouth v Manchester City
                      Starting on 13.2.2017 20:50:00 for 250 minutes (4hrs ish)
                      Channel list is: 01 (720p/uk)  11 (hqlq/us)  113 (720p/uk)  21 (hqlq/ca)  78 (720p/ca)

```

**Comment by markwilkie** [comment]
I hear you that you'd like the ability to capture on certain channels if available.  

To (hopefully) clear up some confusion, the langPref and qualityPref entries are used to determine what order the program tries the channels.  For example, if you put "UK" in langPref and "720p" in quality, then it will put the 720P/UK channel (whatever that is) at the top of the list and try that one first.  Then if it has trouble, it goes to the next one in the list etc.  BTW, which server is used first is determined by the historical rate for that server/channel combination.  The best one is used first...

Finally, if there are multiple retries during the capture attempt itself, (meaning it's going through the server/channel combinations in order, looking for a good one), it keeps track of which server/channel combination worked best and then sticks with that one for the rest of the capture session.

**Comment by tomxslo** [comment]
Thx for clear up - i get it how you get prefered channel..This case is specific, cause in schedule should be monday night football and everything would be okay, instead i have 2 720p channel with UK and channel 1 is on top of that list (but i would like 113 for that case only). Don't worry i will use datetime recording. 

Hm i could use unofficial json schedule: 
http://199.175.52.89/feed.json

There is MNF:

> "Monday Night Football: Pre-Match", "quality": "hqlq", "runtime": "60", "source": "xmltv", "time": "2017-02-13 20:00:00"}, {"category": "tv", "channel": "113", "description": "Bournemouth v Manchester City: Highlights \nBournemouth v Manchester City. Highlights of the Premier League fixture at the Vitality Stadium .", "end_time": "2017-02-13 21:30:00",

**Comment by tomxslo** [comment]
Can you please take a look into my problem with my keywords.json:
> 
> {
>   "Soccer": {
>     "keywords": "EFL,FA Cup,Match of the",
>     "exclude": "",
>     "preMinutes": 5,
>     "postMinutes": 15,
>     "langPref": "uk",
>     "qualityPref": "720P"
>   }
> }

I got mail with that info:

> ned. 12:55-15:00 EFL: Norwich City v Ipswich Town on channel/s 62 (/us) 114 (/uk) 

So in that case program should use 114 channel cause i got  "langPref": "uk"...Right?

But program choose 62 channel:

> 
> 25.2.2017 14:00:04: Queuing show: EFL: Norwich City v Ipswich Town
>                      Starting on 26.2.2017 12:55:00 for 140 minutes (2hrs ish)
>                      Channel list is: 62 (/us)  114 (/uk)  
> 25.2.2017 14:00:04: Starting recording at 26.2.2017 12:55:00 - Waiting for 0 Days, 22 Hours, and 54 minutes.
> 26.2.2017 12:55:01: Peforming speed test to calibrate your internet connection....please wait
> 26.2.2017 12:55:04: Baseline speed: 5 MBytes per second.  (10MB / 2 seconds)
> 26.2.2017 12:55:04: Using the following order of server/channel Pairs:
>                    Server: dEU.UK2 Channel: 62 (/us)  Historical Rate: 138KB/s
>                    Server: dEU.UK1 Channel: 62 (/us)  Historical Rate: 34KB/s
>                    Server: deu.de1 Channel: 62 (/us)  Historical Rate: 8KB/s
>                    Server: deu.nl2 Channel: 62 (/us)  Historical Rate: 6KB/s
>                    Server: deu Channel: 62 (/us)  Historical Rate: 6KB/s
>                    Server: dNAw2 Channel: 62 (/us)  Historical Rate: 5KB/s
>                    Server: deu.nl1 Channel: 62 (/us)  Historical Rate: 4KB/s
>                    Server: deu.nl2 Channel: 62 (/us)  Historical Rate: 6KB/s
>                    Server: deu Channel: 62 (/us)  Historical Rate: 6KB/s
>                    Server: dNAw2 Channel: 62 (/us)  Historical Rate: 5KB/s
>                    Server: dNAw1 Channel: 62 (/us)  Historical Rate: 0KB/s
>                    Server: dEU.UK2 Channel: 114 (/uk)  Historical Rate: 0KB/s
>                    Server: dEU.UK1 Channel: 114 (/uk)  Historical Rate: 0KB/s
>                    Server: deu.de1 Channel: 114 (/uk)  Historical Rate: 0KB/s
>                    Server: deu.nl1 Channel: 114 (/uk)  Historical Rate: 0KB/s
>                    Server: deu.nl2 Channel: 114 (/uk)  Historical Rate: 0KB/s
>                    Server: deu Channel: 114 (/uk)  Historical Rate: 0KB/s
>                    Server: dNAw2 Channel: 114 (/uk)  Historical Rate: 0KB/s
>                    Server: dNAw1 Channel: 114 (/uk)  Historical Rate: 0KB/s
> =========================================
> 26.2.2017 12:55:06: Starting 26.2.2017 12:55:04 on server/channel dEU.UK2/62.  Expect to be done by 26.2.2017 15:15:00.
>                       ffmpeg\bin\ffmpeg.exe -loglevel warning -rw_timeout 5000000 -i "http://dEU.UK2.smoothstreams.tv:9100/viewss/ch62q1.stream/playlist.m3u8?wmsAuthSign=sign==" -c copy D:\Database\Recording\EFL_Norwich_City_v_Ipswich_Town.ts
> 26.2.2017 12:55:09: Settting Timer for 140 minutes in the future to kill process.

**Comment by tomxslo** [comment]
AAA you already did that...Sorry.
