### ISSUE TITLE
Weird behavior today with queuing

### ISSUE THREAD

**Issue by tomxslo** [markwilkie/StreamCapture#37]
I was doing some test today and i have weird behavior with mode2 and queuing...

My json.
{
  "Soccer": {
    "keywords": "Paris,Soccer Special",
    "exclude": "",
    "preMinutes": 15,
    "postMinutes": 30,
    "langPref": "US",
    "qualityPref": "720P"
  }
} 

Program log:
```
14.2.2017 20:09:13: StreamCapture Version 0.99  2/12/2017
14.2.2017 20:09:13: Verifying appsettings....
14.2.2017 20:09:13: Using keywords.json to search schedule. (Please run with --help if you're confused)
=======================
14.2.2017 20:09:14: Queuing show: UCL: Paris Saint-Germain v Barcelona
                      Starting on 14.2.2017 21:00:00 for 165 minutes (2hrs ish)
                      Channel list is: 91 (/uk)
14.2.2017 20:09:14: Show too far away: Ligue 1: Paris Saint Germain v Toulouse at 19.2.2017 20:45:00
14.2.2017 20:09:14: Queuing show: Soccer Special
                      Starting on 14.2.2017 20:15:00 for 195 minutes (3hrs ish)
                      Channel list is: 113 (/uk)
14.2.2017 20:09:14: Queuing show: UCL: Paris Saint-Germain v Barcelona
                      Starting on 14.2.2017 20:30:00 for 165 minutes (2hrs ish)
                      Channel list is: 01 (720p/us)  22 (hqlq/es)  05 (hqlq/us)  72 (720p/es)  89 (/de)
14.2.2017 20:09:14: Sending email...
14.2.2017 20:09:16: Checking the following folders for files older than 30.1.2017 20:09:16
14.2.2017 20:09:16:          logs
14.2.2017 20:09:16:          D:\Database\Recording
14.2.2017 20:09:16: Now sleeping for 5 hours before checking again at 15.2.2017 1:00:00
14.2.2017 20:15:05: Sending email...
14.2.2017 21:00:03: Sending email...
```
In log folder i only have for 2 shows:
[14.2.2017 20:09:14: Queuing show: UCL: Paris Saint-Germain v Barcelona
                      Starting on 14.2.2017 21:00:00 for 165 minutes (2hrs ish)
                      Channel list is: 91 (/uk)  
14.2.2017 20:09:14: Starting recording at 14.2.2017 21:00:00 - Waiting for 0 Days, 0 Hours, and 50 minutes.](url)

and:
[14.2.2017 20:09:14: Queuing show: Soccer Special
                      Starting on 14.2.2017 20:15:00 for 195 minutes (3hrs ish)
                      Channel list is: 113 (/uk)  
14.2.2017 20:09:14: Starting recording at 14.2.2017 20:15:00 - Waiting for 0 Days, 0 Hours, and 5 minutes.
](url)

My email have this:
New Shows Scheduled:
```
Scheduled: UCL: Paris Saint-Germain v Barcelona starting at 14.2.2017 21:00:00 on channel/s 91 (/uk) 
Scheduled: Soccer Special starting at 14.2.2017 20:15:00 on channel/s 113 (/uk) 
Scheduled: UCL: Paris Saint-Germain v Barcelona starting at 14.2.2017 20:30:00 on channel/s 01 (720p/us) 22 (hqlq/es) 05 (hqlq/us) 72 (720p/es) 89 (/de)
``` #

**Comment by tomxslo** [comment]
My mistake - i somehow corrupt file - so it wasnt JSON anymore.

**Comment by markwilkie** [comment]
Actually though, this happened to me too.  This game was in the schedule oddly.  If it happens again, I'll try and accommodate for the "oddness"...

**Comment by tomxslo** [comment]
I have same bug today - i have keywords UCL:

> 15.2.2017 13:42:31: Queuing show: UCL: Real Madrid v Napoli
>                       Starting on 15.2.2017 21:30:00 for 135 minutes (2hrs ish)
>                       Channel list is: 91 (/uk)  
> 15.2.2017 13:42:31: Starting recording at 15.2.2017 21:30:00 - Waiting for 0 Days, 7 Hours, and 47 minutes.
>

**Comment by tomxslo** [comment]
I found wrong entry in json epg:
```
{
"category":"WorldFootball",
"channel":"91",
"description":"",
"end_time":"2017-02-15 17:30:00",
"id":"173658",
"language":"uk",
"name":"UCL: Real Madrid v Napoli",
"network_id":"3515",
"parent_id":"173655",
"quality":"",
"runtime":"120",
"time":"2017-02-15 15:30:00",
"version":"88 (DE) ; 70 (720P / ES) ; 06 (HQLQ / US) ; 23 (HQLQ / ES) ; 08 (720P / US)"
```
},

Why does take that entry from scheule? 91 is UK and should not be selected (i have US langPref) - but the main problem is with schedule json :)

**Comment by markwilkie** [comment]
Looking into this some more

**Comment by markwilkie** [comment]
I mucked about with scheduling quite a bit and (in theory) made things a lot better.  Let me know if this happens again...

**Comment by tomxslo** [comment]
Great it works perfect. Everything was scheduled ok like expected...Thx.
