### ISSUE TITLE
There's been some reported issues in sleep mode

### ISSUE THREAD

**Issue by markwilkie** [markwilkie/StreamCapture#57]
It has been reported that the program stops working when the PC goes into sleep mode.  Not sure the particulars.

**Comment by tomxslo** [comment]
Now is ok - i put one program don't sleep and don't have problem any more.

**Comment by tomxslo** [comment]
Same thing happen today - pc was locked and i need to press ENTER in cmd where StreamRecording is running. 
Now i create script which simulate ENTER command every second to cmd where StreamRecording.exe is running :)

**Comment by markwilkie** [comment]
Have you tried piping the output to a file yet?  Also, what O/S?

**Comment by tomxslo** [comment]
Win10PRO - its working now with my script...

Testing now redirecting output to a file in powershell - will let my conslusion.

**Comment by markwilkie** [comment]
I wonder if PS is relevant...  As it always been within the context of PS that it's "paused"?

**Comment by tomxslo** [comment]
Working with redirecting output to a file also.

**Comment by markwilkie** [comment]
What's the latest here?  Anything to fix?

**Comment by tomxslo** [comment]
No...Its working ok with redirecting...

**Comment by markwilkie** [comment]
Glad to hear
