### ISSUE TITLE
Request: add date option in keywords.json

### ISSUE THREAD

**Issue by tomxslo** [markwilkie/StreamCapture#58]
Is it possible to add date exclude option in keywords.json smt. like that **"daysExclude": "saturday":**

  "EPL": {
    "starredFlag": false, "emailFlag": true,    
    "keywords": ["epl:"],
    "exclude": [],
    "categories": [],
    "preMinutes": 0,
    "postMinutes": 0,
    "langPref": "+us,ca,uk,-de,-es",
    "qualityPref": "+720p",
    "channelPref": ""    
        **"daysExclude": "saturday"**
  }

In saturday there are many 4pm EPL games and i don't want to record all (i know there is concurent options).

But on sunday and other days i would like to record all epl games.
I have this in my json:
 ```
 "EPL": {
    "starredFlag": false, "emailFlag": true,    
    "keywords": ["epl:"],
    "exclude": [],
    "categories": [],
    "preMinutes": 0,
    "postMinutes": 0,
    "langPref": "+us,ca,uk,-de,-es",
    "qualityPref": "+720p",
    "channelPref": ""    
  }


```

**Comment by markwilkie** [comment]
Sorry, I don't think I'm going to get to this.
