### ISSUE TITLE
Request: add timezone for schedTimeOffset

### ISSUE THREAD

**Issue by tomxslo** [markwilkie/StreamCapture#60]
One really low prio request or idea;
Today was the problem with schedule time, becuase daylight saving time in USA.
It would be good, if you can put timezone in schedTimeOffset, so you don't need to change manualy time.

**Comment by markwilkie** [comment]
I looked into this and it's pretty dangerous.  It can be magical when it works, but having a set offset is a lot more safe.

For daylight savings time, I'm now deleting the cached recordings, so it should be OK if the first schedule of the "day" is after 2am.  I'm planning on setting my first schedule grab of the day at 3am.
