### ISSUE TITLE
Feature: Add ability to configure via http interface

### ISSUE THREAD

**Issue by markwilkie** [markwilkie/StreamCapture#63]
Perhaps add a mini-web server to allow for configuration.  Especially, special add and/or cancellations of schedule entries.

**Comment by markwilkie** [comment]
https://www.codeproject.com/articles/137979/simple-http-server-in-c

**Comment by tomxslo** [comment]
That feature would be fantastic...Looking forward.

**Comment by markwilkie** [comment]
Done and merged into master
