### ISSUE TITLE
dotnet build & dotnet build -r win10-x64 only generate .dll file

### ISSUE THREAD

**Issue by smokechaser01** [markwilkie/StreamCapture#65]
As the readme suggests I first did a dotnet restore and then a dotnet build. This gave me a dll file. So then I tried to do a "dotnet build -r win10-x64" as it was suggested would generate an .exe but in fact it does not, it still only generates a .dll file. 

------

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

C:\Users\MYUSER\Downloads\StreamCapture-master>dotnet build -r win10-x64
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  StreamCapture -> C:\Users\MYUSER\Downloads\StreamCapture-master\bin\Debug\netcoreapp2.0\win10-x64\StreamCapture.dll

Only get a dll file...

**Comment by markwilkie** [comment]
I have updated the readme.md with more details.  Hopefully that helps clear things up.
