### ISSUE TITLE
Gmail SMTP error with port 587

### ISSUE THREAD

**Issue by chansters** [markwilkie/StreamCapture#79]
I'm getting this error message when using port 587 with smtp.gmail.com

> ERROR: Problem sending mail.  Error: The remote certificate is invalid according to the validation procedure.
> 

The discussion in this thread may shed some light on the issue ? 

https://github.com/jstedfast/MailKit/issues/307

I'm on Mac OS X 10.12.4.

**Comment by markwilkie** [comment]
This looks like it might be a work-around:

You need ignore this validation if you had problemas with certificate.

client.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => {
return true;
};

**Comment by chansters** [comment]
Thanks Mike - which file do I need to edit to insert this workaround ?

**Comment by markwilkie** [comment]
https://github.com/markwilkie/StreamCapture/blob/master/Mailer.cs#L131 should do the trick.  Feel free to submit a PR when you get it working.  Thanks!

**Comment by chansters** [comment]
My apologies Mike, I'm really not all that technical.  :P 

Is this the right place to insert the workaround in Mailer.cs 

                using (var client = new SmtpClient())
                {
                    client.Connect(configuration["smtpServer"], Convert.ToInt16(configuration["smtpPort"]), false);
                    client.AuthenticationMechanisms.Remove("XOAUTH2");  
                    client.Authenticate(configuration["smtpUser"], configuration["smtpPass"]);
                   **client.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) 
                     => {
                             return true;
                           };**
                    client.Send(message);
                    client.Disconnect(true);
                }

**Comment by markwilkie** [comment]
Merged
