### ISSUE TITLE
Datetime recording not working

### ISSUE THREAD

**Issue by tomxslo** [markwilkie/StreamCapture#86]
@:[/opt/SS]: ./StreamCapture --channels 10 --duration 10 --filename test --datetime "06/08/2017 11:09"
6/8/17 10:50:50 AM: StreamCapture Version 2.03 5/16/2017
6/8/17 10:50:50 AM: Verifying appsettings....
6/8/17 10:50:50 AM: Verifying command line options passed in....
6/8/17 10:50:53 AM: Queuing show:  Starting on 6/8/17 11:09:00 AM for 10 minutes (0hrs ish)
6/8/17 10:50:53 AM: Starting recording at 6/8/17 11:09:00 AM - Waiting for 0 Days, 0 Hours, and 18 minutes.
======================
6/8/17 10:50:53 AM: ERROR - Exception!
======================
Object reference not set to an instance of an object.
   at StreamCapture.Recorder.QueueRecording(ChannelHistory channelHistory, RecordInfo recordInfo, IConfiguration configuration, Boolean useLogFlag) in /home/tomx/Templates/StreamCapture/Recorder.cs:line 253
6/8/17 10:50:53 AM: Sending email...
[/opt/SS]:

**Comment by markwilkie** [comment]
Fixed (finally)
