### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by paulsavo1** [markwilkie/StreamCapture#94]
Can someone please confirm if this continues to work? it just stopped working for me for no reason and i try to recompile i get errors

**Comment by markwilkie** [comment]
sorry Paul, I wasn't getting notifications for whatever reason off the board.  Yes, I still use this everyday.  About to watch Liverpool in fact....   :)

Go ahead and post back on the board as I should see it now and we'll see if we can get things sorted.
